### ISSUE TITLE
Auto-renumber lines

### ISSUE THREAD

**Issue by ukanuk** [KnoP-01/vim-tp#3]
I found that these commands will update the line numbers in a file, so I'm executing this before I save in order to update line numbers.

Do you know how to make these commands happen automatically when saving? It looks like you're automatically fixing line endings in `ftdetect`, so maybe this could get added there somehow? 

```
:let i=1
:%s/^\s*\d\+:/\=printf('%4d:', i.execute('let i+=1'))/g
```

**Comment by KnoP-01** [comment]
Since vim-tp has no ftplugin and I don't plan to create one you need to do this yourself.

Not thoroughly tested but try this in your .vimrc or in ~/.vim/after/tp.vim
```vim
augroup MyLsWrite
  au! BufWritePre *.ls\c call FixLineNumOnLsWrite()
augroup END
function! FixLineNumOnLsWrite() abort
  let i = 1
  %s/^\s*\d\+:/\=printf('%4d:', i.execute('let i+=1'))/g
  unlet i
endfunction
```

> It looks like you're automatically fixing line endings in ftdetect

Yeah, that's actually a nasty hack. I don't like it but it works so that the file appears not modified if this is done in ftdetect.

**Comment by KnoP-01** [comment]
For your interest: 

Fanuc ASCII-upload as well as WinOLPC don't need correct line numbers to load the file. Any line number will do.

**Comment by KnoP-01** [comment]
Oh, it has an ftplugin ;)

Yeah well... maybe one day I will integrate that.

**Comment by ukanuk** [comment]
Thank you for the guidance! Here's what I'm using for now:

File: `~\vimfiles\after\ftplugin\tp.vim`

```viml
augroup MyLsWrite
  au! BufWritePre *.ls call FixLineNumOnLsWrite()
  au! BufWritePre *.pe call FixLineNumOnLsWrite()
augroup END
function! FixLineNumOnLsWrite() abort
  let l:winview = winsaveview()
  let i = 1
  %s/^\s*\d\+:/\=printf('%4d:', i.execute('let i+=1'))/g
  unlet i
  call winrestview(l:winview)  
endfunction
```

**Comment by KnoP-01** [comment]
@ukanuk: This way your auto commands will end up in the augroup filetypedetect, not the augroup MyLsWrite.

Let me suggest the following changes.

```vim
augroup auTpOnBufWritePre
  au! BufWritePre \c*.ls,\c*.pe call FixLineNumOnTpWrite()
augroup END
function! FixLineNumOnTpWrite() abort
  let l:winview = winsaveview()
  let l:i = 1
  %s/^\s*\d*:/\=printf('%4d:', l:i.execute('let l:i+=1'))/g
  call winrestview(l:winview)  
endfunction
```

- Fix augroup
- Explicitly use script local variable l:xxx
- No need to unlet script local
- Put both filetype pattern in one line
- Use \d* instead of \d\+ so that empty line numbers also get fixed. Only the colon must be present.

**Comment by ukanuk** [comment]
Thank you for teaching me and improving it! I did not know what `l:` and `g:` mean, and now I do!

**Comment by ukanuk** [comment]
It seems numbers are required after all for FANUC to deal with exceptionally line lines. I tried transferring this LS file with this to robot but got error ASBN-009 / ASBN-092 / on line XX, column xx / Undefined Instruction

```
  13:  LBL[1:CHECK FEEDBACK] ;
  14:  WAIT (DI[1033:Clamp 1 Unclamped]=ON AND DI[1041:Clamp 1 Clamped]=OFF AND DI[1034:Clamp 2 Unclamped]=ON AND DI[1042:Clamp 2 Clamped]=OFF AND DI[1035:Clamp 3 Unclamped]=ON AND DI[1043:Clamp 3 Clamped]=OFF AND 
  15:  DI[1036:Clamp 4 Unclamped]=ON AND DI[1044:Clamp 4 Clamped]=OFF) TIMEOUT,LBL[99] ;
  16:   ;
  17:  GO[6:USER FAULT CODE]=0 ;

```

This code was accepted (and this is how FANUC numbered it):

```
  13:  LBL[1:CHECK FEEDBACK] ;
  14:  WAIT (DI[1033:Clamp 1 Unclamped]=ON AND DI[1041:Clamp 1 Clamped]=OFF AND DI[1034:Clamp 2 Unclamped]=ON AND DI[1042:Clamp 2 Clamped]=OFF AND DI[1035:Clamp 3 Unclamped]=ON AND DI[1043:Clamp 3 Clamped]=OFF AND 
    :  DI[1036:Clamp 4 Unclamped]=ON AND DI[1044:Clamp 4 Clamped]=OFF) TIMEOUT,LBL[99] ;
  15:   ;
  16:  GO[6:USER FAULT CODE]=0 ;
```

So, I will keep using `\d\+` instead of `\d*`

**Comment by KnoP-01** [comment]
Right, in continued long lines there must not be a line number. Good catch! I'll keep that in mind in case I integrate it into the ftplugin.

**Comment by ukanuk** [comment]
By the way in order to get this working for me in nvim, I had to take the code from the `after` directory `nvim-data/site/after/ftplugin/tp.vim` and move it to the end of the existing file under `nvim-data/site/ftplugin/tp.vim`. It still seems to work fine with regular vim, too: 

vimfiles\ftplugin\tp.vim
```
" Fanuc TP file type plugin for Vim
" Language: Fanuc TP
" Maintainer: Patrick Meiser-Knosowski <knosowski@graeffrobotics.de>
" Version: 1.0.0
" Last Change: 16. Jun 2023
"
" Suggestions of improvement are very welcome. Please email me!
"
" ToDo's {{{
" }}} ToDo's

" Only do this when not done yet for this buffer
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

let s:keepcpo = &cpo
set cpo&vim

setlocal suffixesadd+=.ls
setlocal suffixesadd+=.LS
setlocal suffixesadd+=.pe
setlocal suffixesadd+=.PE

nnoremap <silent><buffer> <leader>dc :%s/\(LBL\)\@<![\[,]\d\+\zs:[^\]]*//g<CR>
let b:undo_ftplugin = "setlocal sua<"

let b:match_ignorecase = 1
let b:match_words = '\<IF\>.*:\<ELSE\>.*:\<ENDIF\>.*'

let &cpo = s:keepcpo
unlet s:keepcpo

" vim:sw=2 sts=2 et fdm=marker

augroup auTpOnBufWritePre
  au! BufWritePre \c*.ls,\c*.pe call FixLineNumOnTpWrite()
augroup END
function! FixLineNumOnTpWrite() abort
  let l:winview = winsaveview()
  let l:i = 1
  %s/^\s*\d\+:/\=printf('%4d:', l:i.execute('let l:i+=1'))/g
  call winrestview(l:winview)
endfunction

```

**Comment by KnoP-01** [comment]
I look into it when I have some spare time. Thanks.
