### ISSUE TITLE
Highlighting for IF THEN ELSE ENDIF

### ISSUE THREAD

**Issue by ukanuk** [KnoP-01/vim-tp#4]
After a bit of research I believe it's possible vim can properly highlight the IF THEN ELSE ENDIF statement regions. Documenting my findings here, for if/when I want to take a stab at it (or someone else).

Huh, perhaps this could even apply to JMP/LBL statements. Not finding anything on google though for matching goto/labels.

Sample FANUC TP/LS syntax with nested if-else inside of a regular if:
```ls
   1:  IF (R[6]=1) THEN ;
   1:L PR[13] 3000mm/sec CNT100    ;
   1:  IF (R[7]=1),JMP LBL[999] ;
   1:  IF (DI[1118]=ON AND DI[1119]=OFF) THEN ;
   1:L PR[14] 3000mm/sec CNT100    ;
   1:  ELSE ;
   1:L PR[15] 3000mm/sec CNT100    ;
   1:  ENDIF ;
   1:  ENDIF ;
   1:  LBL[999] ;
   1:  END ;
```

Sample ifdef code block I found
- https://stackoverflow.com/questions/26624020/vim-how-to-highlight-code-inside-ifdef-endif-block
- https://github.com/vim-scripts/ifdef-highlighting
- https://stackoverflow.com/questions/8601280/in-vim-how-to-check-the-ifdef-macro-i-am-currently-inside
```c
#ifdef BLA
    #if BLO == 1
        #include <something>
    #else
        #pragma error "oops"
    #endif
#elifdef BLU
    #include <something_else>
#endif
```

**Comment by KnoP-01** [comment]
I don't understand the goal you want to achieve by using a region for IF/ELSE/ENDIF. What should the end result look like?

Regarding labels: I think they're not comparable to IF/ENDIF, since one can have a lot of JUMPs to the same LABEL.

**Comment by ukanuk** [comment]
See the nice gif on https://github.com/andymass/vim-matchup and more discussion at https://vi.stackexchange.com/q/8707/28977

**Comment by KnoP-01** [comment]
Ah, now I get it. You want support for MatchUp. This has nothing to do with a highlight region. 

MatchIt/MatchUp-support added for IF/ELSE/ENDIF in e4d9878.

Anything else?

**Comment by KnoP-01** [comment]
@ukanuk Thanks for your suggestion. Since there is no more feedback I assume this issue fixed.

**Comment by ukanuk** [comment]
Please see pull request #5 for adding FOR loop support.

Sorry for the delay, I was trying to get JMP/LBL highlighting working as well but still haven't figure it out. This is the best I could come up with, but it only highlights in one single condition -- when cursor is on a LBL with a match above it in the document. 
```
let b:match_words = '\<IF\>.*:\<ELSE\>.*:\<ENDIF\>.*,'
\ . '\<FOR\>.*:\<ENDFOR\>.*,'
\ . 'LBL\[\(\d\+\):LBL\[\1'
```

I would expect JMP/LBL matchup support to allow using `%` to jump from a goto to the matching label and vice-versa. And similar to multi-part if-elif-elif-else-endif statements, I would expect gotoA-gotoA-gotoA-labelA to all be highlighted at the same time and `%` to cycle through each match.

In example in this snippet, highlight all three of the `LBL[91` whenever one is selected. And then `%` should allow cycling through them.
```
LBL[11:Main process] ;
WAIT (DI[1105:SIGNAL END]=ON) TIMEOUT,LBL[91] ;
WAIT (DI[1106:SIGNAL START]=OFF) TIMEOUT,LBL[91] ;
LBL[12] ;
IF (DI[1118:RESULT GOOD]),JMP LBL[19] ;
WAIT (DI[1114:PARTIAL POSITION]) TIMEOUT,LBL[92] ;
WAIT (DI[1113:HOME POSITION]) TIMEOUT,LBL[93] ;
LBL[19:END PROCESS] ;
END ;
LBL[91:ERROR0] ;
LBL[92:ERROR1] ;
JMP LBL[11] ;
LBL[93:ERROR2] ;
JMP LBL[12] ;
````

**Comment by KnoP-01** [comment]
Merged your FOR addition with a slightly modified commit message.

The JMP/LBL thing is tricky though. Maybe I find time next week to look into it. Possible that it will not work at all.

**Comment by KnoP-01** [comment]
@ukanuk: I don't think it is possible to make matchit/matchup working for jump/label, since there is no distinct start and end. 

You see, a switch/case/default/endswitch (using krl as an example here) has a distinct start (switch), a distinct end (endswitch) and stuff that can appear in between (case/default). This is not the case with jump/label. The only thing is the label which is unique, but jumps may be further up or down or even both. And no one knows how many jumps there are. And there may be indirect jumps, so even if one could make it work it would be inaccurate. 

I will not put more energy into this. However, if you manage to make it work I'm happy to include your pull request.

**Comment by ukanuk** [comment]
Huh, interesting side note my half-broken JMP/LBL matching found an actual code issue for me already. Typically I have a list of error indices at the end of my program, and as I was clicking through them I noticed some weren't highlighting the previous match. Lo and below, it was a code issue and I had to fix the JMP/LBL indices to match up again and delete a no-longer-used label.

**Comment by ukanuk** [comment]
By the way in order to get this working for me in nvim, I had to take the code from the `after` directory `nvim-data/site/after/ftplugin/tp.vim` and move it to the end of the existing file under `nvim-data/site/ftplugin/tp.vim`. It still seems to work fine with regular vim, too: 

vimfiles\ftplugin\tp.vim
```
" Fanuc TP file type plugin for Vim
" Language: Fanuc TP
" Maintainer: Patrick Meiser-Knosowski <knosowski@graeffrobotics.de>
" Version: 1.0.0
" Last Change: 16. Jun 2023
"
" Suggestions of improvement are very welcome. Please email me!
"
" ToDo's {{{
" }}} ToDo's

" Only do this when not done yet for this buffer
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

let s:keepcpo = &cpo
set cpo&vim

setlocal suffixesadd+=.ls
setlocal suffixesadd+=.LS
setlocal suffixesadd+=.pe
setlocal suffixesadd+=.PE

nnoremap <silent><buffer> <leader>dc :%s/\(LBL\)\@<![\[,]\d\+\zs:[^\]]*//g<CR>
let b:undo_ftplugin = "setlocal sua<"

let b:match_ignorecase = 1
let b:match_words = '\<IF\>.*:\<ELSE\>.*:\<ENDIF\>.*'

let &cpo = s:keepcpo
unlet s:keepcpo

" vim:sw=2 sts=2 et fdm=marker

augroup auTpOnBufWritePre
  au! BufWritePre \c*.ls,\c*.pe call FixLineNumOnTpWrite()
augroup END
function! FixLineNumOnTpWrite() abort
  let l:winview = winsaveview()
  let l:i = 1
  %s/^\s*\d\+:/\=printf('%4d:', l:i.execute('let l:i+=1'))/g
  call winrestview(l:winview)
endfunction

```
